### ISSUE TITLE
Add option for limiting rows of retrieved of results

### ISSUE THREAD

**Issue by bburky** [pydata/pandas-gbq#102]
I found the pandas-gbq interface easy to use and wanted to also use it for creating tables in BigQuery, not just downloading all the results at once. The existing capabilities of read_gbq() is actually already sufficient to do this, because you can just set `query.destinationTable` in the job configuration. However, I would like to limit the number of retrieved rows to a small sample of the whole table that was created instead of downloading the many thousands of rows that were created.

I've already played with making the changes myself in a project I'm working on:

http://nbviewer.jupyter.org/github/bburky/subredditgenderratios/blob/master/Subreddit%20Gender%20Ratios.ipynb

In the [current code](https://github.com/pydata/pandas-gbq/blob/4cab83cefb7df190bf3e5b43168c2cb53f596c31/pandas_gbq/gbq.py#L547) for run_query(), you read all rows from the table by converting the iterator into a list. Instead, you could pass the iterator to `itertools.islice()` first to limit it to a configurable limit. You can look at my code to see how it could be done.

Also, if you're interested I could contribute the IPython `%%bigquery` cell magic I am using in that project. It should be a very simple wrapper around `read_gbq()`.

**Comment by maxim-lian** [comment]
Adding the `%%bigquery` magic would be interesting. How similar is that to the magic in google's datalab?

**Comment by bburky** [comment]
Oh, I didn't know about datalab. My `%%bigquery` magic is basically a thin wrapper around `read_gbq()`. I can't quite tell how datalab's `%%bq` magic works, it may do something similar around their own APIs. They also have a `--name` argument for reusing results, but I can't tell if it saves tables, or just lets you save the output to a variable for reuse.

Would work on an IPython magic be done in this repository, or a separate standalone one? It would introduce a dependency on IPython.

**Comment by maxim-lian** [comment]
> Would work on an IPython magic be done in this repository, or a separate standalone one? It would introduce a dependency on IPython.

I'm not sure actually (it could be an optional dependency though). @jreback @tswast ?

**Comment by jreback** [comment]
you can do it in this repo; it a separate piece so the dep is fine (and only impacts the magic piece)

**Comment by tswast** [comment]
Yeah, could be an optional dependency.

@bburky: My coworker @alixhami has started some work on making a `%%bigquery` magic, too. He's planning on sending a PR soon to https://github.com/GoogleCloudPlatform/google-cloud-python to add the magic command there. You may wish to coordinate.

**Comment by tswast** [comment]
Follow-up for magics, the `google-cloud-bigquery` library is adding a BigQuery magic in https://github.com/GoogleCloudPlatform/google-cloud-python/pull/4983

**Comment by tswast** [comment]
> Re limiting rows - that's very easy to do with a LIMIT clause

The issue was opened with the thought that you could do a query with a lot of results and write to a destination table, but only want to sample the results.

> However, I would like to limit the number of retrieved rows to a small sample of the whole table that was created instead of downloading the many thousands of rows that were created.

Limiting the maximum results via `pandas-gbq` probably doesn't make the most sense if you want a representative sample. For that you'd want to add a little randomness and select from the destination table.

Or @bburky did you not want a representative sample, more just a preview?

**Comment by maxim-lian** [comment]
Ah, preview makes sense. Sorry for being overzealous.

**Comment by bburky** [comment]
Yes. I was running a query that returned many many results and saving the
results with `query.destinationTable`. To sanity check the query I ran, I
wanted to see a 100 row preview or so.

A possible implementation is just `itertools.islice()` of the query
results. I don't mind if this isn't completely built into pandas-gbq, but
there wasn't any way for me to hook or modify anything except copy pasting
and modifying `run_query()`.
