### ISSUE TITLE
_parse_data fails when Rows object has only one column and one row

### ISSUE THREAD

**Issue by csmc88** [pydata/pandas-gbq#114]
When making a call to `parse_data` in `pandas-gbq/gbq.py` I'm getting the following error.

```
TypeError: 'int' object has no attribute '__getitem__'
```

I'm attempting to recover results from a Google Big Query table. However, I'm expecting a single  numeric value in a 1x1 table. This can be reproduced manually with the following inputs to `_parse_data`. 

```
schema = {'fields':[{'type': u'integer',
                     'mode': u'nullable',
                     'name': u'test_count'
                    }
                   ]
         }
pages = [Row((36678925,), {u'test_count': 0})]
```

Where `Row` is an object from module `google.cloud.bigquery.table`

This causes `_parse_data` to fail at line 751

`field_value = entries[col_num]`

Since the value in `entries` is not a dict but an integer with no `__getitem__`.

**Comment by tswast** [comment]
Thanks for the report. Is there a query that reproduces this issue? I imagine this could be a problem with the upstream library [google-cloud-python](https://github.com/GoogleCloudPlatform/google-cloud-python) if it is supposed to return a Row but doesn't

**Comment by maxim-lian** [comment]
Do you have a stack trace to hand?
