### ISSUE TITLE
Printing rather than logging?

### ISSUE THREAD

**Issue by maxim-lian** [pydata/pandas-gbq#12]
We're printing in addition to logging, when querying from BigQuery. This makes controlling the output much harder, aside from being un-idiomatic.

Printing in white, logging in red:

https://cloud.githubusercontent.com/assets/5635139/23176541/6028b884-f831-11e6-911a-48aa7741a4da.png

**Comment by MaximilianR** [comment]
I think the ideal design is to remove the [`verbose` kwd](https://github.com/pandas-dev/pandas/blob/master/pandas/io/gbq.py#L146), and log with `INFO` or `WARNING` depending on the severity

**Comment by jreback** [comment]
@MaximilianR that sounds good, as generally better to simply log, and people can connect to the console if desired. though I could see a kw controlling this too (as on an interactive query you simply want to have the printing and just easier), maybe ``verbose='print'``.

**Comment by MaximilianR** [comment]
> as on an interactive query you simply want to have the printing and just easier

IPython shows logs assuming they are `WARNING` or above, by default, is that still necessary?

```python
In [1]: import logging

In [2]: logger = logging.getLogger()

In [3]: logger.info('test')

In [4]: logger.warning('test')
test
```

**Comment by jreback** [comment]
oh maybe that's better. feel free to do a PR!

**Comment by jreback** [comment]
@MaximilianR PR for this?

**Comment by MaximilianR** [comment]
OK

**Comment by jreback** [comment]
@MaximilianR bugging you!

**Comment by MaximilianR** [comment]
Thank you for bugging me! I need to get better at pushing these over the line - I have a burst of enthusiasm and then finishing it can feel less exciting... I need a few days to get stuff back in order after traveling and then will aim to do this next week

**Comment by tswast** [comment]
I've updated the changelog to include this change in https://github.com/pydata/pandas-gbq/pull/152

**Comment by QuinRiva** [comment]
With the update and the changes to logging, I can't seem to get the progress status of downloading the results of the query.  Previously it would print an output after each page was downloaded (ever 30,000 rows or so) - no it only logs when everything has finished downloading.

I have tried using logging.INFO and logging.DEBUG, but neither gives me the desired output.  When downloading a table with millions of records, download progress is very useful.

`Requesting query... 
ok.
Query running...
Job ID: xxxx
Query running...
Got 242716 rows.

Total time taken 21.52 s.
Finished at 2018-05-23 13:51:13`

**Comment by maxim-lian** [comment]
@QuinRiva do you seeing logging output generally? If you run `logging.info('test')`, do you see that? If not, you likely need to change your logging config. 

If you do see that, it's likely a pandas-gbq issue

**Comment by tswast** [comment]
It's true that no download progress is given. The trouble line is at

https://github.com/pydata/pandas-gbq/blob/08166685d3305a57fbfd3bc4c41a1cf5df98ebcf/pandas_gbq/gbq.py#L298

This behavior was not caused by the logging change. We could open a separate issue to track download progress for queries (there's already one open for load jobs).

**Comment by QuinRiva** [comment]
This is just in comparison to previous behaviour where progress was shown, see below using an older version of pandas-gbq:
```
In [5]
sql = "SELECT * From mySchema.myTable"
df = gbq.read_gbq(query=sql, dialect ='standard', project_id=project_id)
```

```
In [10]
Requesting query... ok.
Job ID: job_eCcpDr75589IEbgmp-ybEObz15lk
Query running...
Query done.
Processed: 41.3 MB
Standard price: $0.00 USD

Retrieving results...
  Got page: 1; 4% done. Elapsed 12.59 s.
  Got page: 2; 8% done. Elapsed 16.59 s.
  Got page: 3; 12% done. Elapsed 21.28 s.
  Got page: 4; 15% done. Elapsed 25.89 s.
  Got page: 5; 19% done. Elapsed 31.18 s.
  Got page: 6; 23% done. Elapsed 35.24 s.
  Got page: 7; 27% done. Elapsed 39.45 s.
  Got page: 8; 31% done. Elapsed 44.6 s.
  Got page: 9; 35% done. Elapsed 48.34 s.
  Got page: 10; 39% done. Elapsed 53.03 s.
  Got page: 11; 42% done. Elapsed 57.66 s.
  Got page: 12; 46% done. Elapsed 62.37 s.
  Got page: 13; 50% done. Elapsed 66.85 s.
  Got page: 14; 54% done. Elapsed 70.75 s.
  Got page: 15; 58% done. Elapsed 75.48 s.
  Got page: 16; 62% done. Elapsed 80.07 s.
  Got page: 17; 66% done. Elapsed 84.81 s.
  Got page: 18; 69% done. Elapsed 89.05 s.
  Got page: 19; 73% done. Elapsed 93.37 s.
  Got page: 20; 77% done. Elapsed 98.09 s.
  Got page: 21; 81% done. Elapsed 102.59 s.
  Got page: 22; 85% done. Elapsed 107.73 s.
  Got page: 23; 89% done. Elapsed 113.71 s.
  Got page: 24; 93% done. Elapsed 119.53 s.
  Got page: 25; 96% done. Elapsed 125.56 s.
  Got page: 26; 100% done. Elapsed 130.1 s.
Got 323841 rows.

Total time taken 142.13 s.
Finished at 2018-01-22 08:13:03.
```

**Comment by maxim-lian** [comment]
Yes; we're logging rather than printing now.

We need to discover whether the issue is with your setup or the library. Could you try `import logging; logging.info('hello')`, and see whether you can see `hello`?

**Comment by tswast** [comment]
I've filed https://github.com/pydata/pandas-gbq/issues/182 to track the feature request of adding a progress indicator during the "download" step.

**Comment by QuinRiva** [comment]
Yes, it appears the logging works fine - it's just the post query downloading that isn't locked, but it looks like @tswast is on top of it.

But for reference:
```
In [3]:
import logging
import sys
logger = logging.getLogger('pandas_gbq')
logger.handlers=[]
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler(stream=sys.stdout))

from pandas.io import gbq
project_id='myProjectId'
sqlCost = """SELECT *
	From mySchema.myTable
    """
# sqlCost = bq.Query(sqlCost)
# cost = sqlCost.execute(output_options=bq.QueryOutput.dataframe()).result()
cost = gbq.read_gbq(query=sqlCost, dialect ='standard', project_id=project_id)
cost.head()
```

Output:
```
Requesting query... 
ok.
Query running...
Job ID: dec4efc9-9809-49aa-8073-4c3cc83d2cc1
Query running...
Query done.
Processed: 34.7 MB Billed: 35.0 MB
Standard price: $0.00 USD

Got 249197 rows.

Total time taken 81.51 s.
Finished at 2018-05-23 17:28:00.
```

**Comment by Joao-Martins-farfetch** [comment]
How can I remove any log?
I build an interface but the amount of logs is too big and user get confused by what it is.
thank you!
