### ISSUE TITLE
TST: Unit tests in `test_gbq.py` aren't running

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#135]
As pointed out in https://github.com/pydata/pandas-gbq/pull/125, `pytest` was skipping the unit tests in `test_gbq.py`. Many of the unit tests are now failing due to other changes. I've created a `unit-tests` branch to push fixes to the unit tests before we merge the class rename to `master`.

**Comment by maxim-lian** [comment]
Closed by https://github.com/pydata/pandas-gbq/pull/147
