### ISSUE TITLE
Uploading DateTime field via to_gbq() leads to missing seconds/milliseconds data

### ISSUE THREAD

**Issue by ptrvtch** [pydata/pandas-gbq#151]
I used the following code to reproduce the issue:
```python
import pandas as pd, pandas_gbq
data = {"date": datetime.datetime.now()} # 2018-03-22 13:27:03.230384
df = pd.DataFrame(data, index=[0]

destination_table = 'test_tables.test_datetime'
project_id = 'my-project-11111'
private_key = 'path-to-key.json'
pandas_gbq.to_gbq(
  df,
  destination_table,
  project_id,
  private_key=private_key
)
```

When I check the values in the created table in Google BigQuery, the value doesn't keep seconds and milliseconds part of the DateTime:  `2018-03-22 13:27:00.000 `

Standard bigquery library doesn't have this problem.

**Comment by maxim-lian** [comment]
Thanks for the report. This was fixed by https://github.com/pydata/pandas-gbq/pull/148. Please reopen if you see this problem on master
