### ISSUE TITLE
`verbosity` warning is overzealous

### ISSUE THREAD

**Issue by craigcitro** [pydata/pandas-gbq#157]
I just installed 0.4.0 (🎉), and a call to `read_gbq` with no `verbose` argument still complained at me.

I realized the issue is because pandas [still provides a default](https://github.com/pandas-dev/pandas/blob/6d610a4d9393c0d0335267dc3252ccabb9e51e43/pandas/io/gbq.py#L25).

WAI?

(/cc @tswast)

**Comment by tswast** [comment]
Thanks for trying it out!

Oops. Yeah, we should set the default to None here. Probably worth a little 0.4.1 update for that fix.

It's still a problem for folks that  use it upstream from Pandas. I'll update the default there in my PR to update the docs: https://github.com/pandas-dev/pandas/pull/20564 (I started that one before I released 0.4.0, so probably due for a little refresh anyway)

**Comment by maxim-lian** [comment]
Yup, that's my fault, apologies

**Comment by craigcitro** [comment]
Thanks @tswast! Are you planning an 0.4.1 update?

**Comment by tswast** [comment]
Yep, @craigcitro Just released to PyPI.
