### ISSUE TITLE
Tests failing on master

### ISSUE THREAD

**Issue by maxim-lian** [pydata/pandas-gbq#168]
@tswast do you recognize these? https://travis-ci.org/pydata/pandas-gbq/jobs/364877445

I can't immediately see how 8f49ec3f134cc0a85f541116c42647c515fdc7e6 could have caused those

**Comment by tswast** [comment]
```
self = <MagicMock name='mock.query()' spec='QueryJob' id='139858594198360'>
name = 'job_id'
    def __getattr__(self, name):
        if name in ('_mock_methods', '_mock_unsafe'):
            raise AttributeError(name)
        elif self._mock_methods is not None:
            if name not in self._mock_methods or name in _all_magics:
>               raise AttributeError("Mock object has no attribute %r" % name)
E               AttributeError: Mock object has no attribute 'job_id'
.nox/test35/lib/python3.5/site-packages/mock/mock.py:698: AttributeError
```

Odd. I would have thought the QueryJob spec would have worked here. I can't think of any changes in google-cloud-bigquery that would have caused it.

**Comment by tswast** [comment]
I think the problem is that the Job class in [BigQuery 0.29.0 does have a job_id](https://github.com/GoogleCloudPlatform/google-cloud-python/blob/bigquery-0.29.0/bigquery/google/cloud/bigquery/job.py#L161), but it is not an `@property`, so Mock can't find it on that version.
