### ISSUE TITLE
load job config allow quoted newlines 

### ISSUE THREAD

**Issue by jwBoral** [pydata/pandas-gbq#180]
https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/load.py

needs to add the condition

job_config.allow_quoted_newlines = True 

current work around is: 
df = df.replace({'\n': ' ', '\r\n': ' ', '\r': ' '}, regex=True)

**Comment by tswast** [comment]
I think we could safely always turn this option on. I see the fact that we serialize to CSV as an implementation detail.

**Comment by tswast** [comment]
Closed by #230
