### ISSUE TITLE
option to suppress index column in to_gbq

### ISSUE THREAD

**Issue by dkapitan** [pydata/pandas-gbq#194]
Not sure if this has been requested before. I would like to be able to suppress the index column of the dataframe when using `df.to_gbq`.

Would like to hear if this is a reasonable request. If so, I would be happy to contribute (medior experience with Python) if someone could point me in te right direction where to add this feature.

**Comment by max-imlian** [comment]
Thanks for posting the issue @dkapitan .

Could you clarify what you mean by 'suppress'? We currently discard the index with `index=False`:

https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/load.py#L17

**Comment by dkapitan** [comment]
Thanks for your prompt response @max-imlian. Indeed I meant to discard the index as is currently implementerd.

Have had another look at it, and feeling an absolute noob: the new BigQuery interface shows 'Row' as the first column when previewing the data. I thought that was a proper column in the table schema. Which it isn't .... 🤣
