### ISSUE TITLE
Improve code coverage when gbq credentials are not provided

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#20]
By default, the majority of pandas-gbq unit tests are skipped on forks of pandas-gbq because Google BigQuery integration testing requires credentials. This causes code coverage to appear low on pull requests from forks. One potential way to increase the code coverage reported in pull requests from forks is to use `mock` to stub external requests.
https://docs.python.org/3.6/library/unittest.mock.html

**Comment by jreback** [comment]
yeah I realized that now :>

we have a very low check on the PR's anyhow

**Comment by maxim-lian** [comment]
@tswast is there any interface Google provides that would allow testing against BQ without an account / with a limited-google-provided-account? At the moment people can't run tests without a google account (and given https://github.com/pydata/pandas-gbq/issues/109, without downloading a json file and putting it in a specific path)

**Comment by tswast** [comment]
A local emulator would be a good way to provide such a use-case. Google has them for some services like Bigtable and Cloud Pub/Sub, but there isn't one for BigQuery.

**Comment by maxim-lian** [comment]
OK thanks. 
This might be a long-shot, but do you think Google might be willing to provide some keys we could put in the repository so, for example, any PR pushed to Travis would test?

**Comment by tswast** [comment]
I believe this project already has some secret keys used to build on merge.

Some CI systems allow accessing secret keys after a PR from a fork has been manually reviewed by adding a GitHub tag/label to the PR. I don't believe Travis has this feature, though.

**Comment by maxim-lian** [comment]
ok thx

**Comment by max-sixty** [comment]
Unfortunately I don't think there's a BigQuery mocking library like there is with some other Google products. I agree that would radically improve the testing iteration. 

But until then, I propose to close this as out-of-scope; unless people think I'm overestimating how difficult it would be to build the mocks

**Comment by tswast** [comment]
Yeah, no BigQuery emulator. It does make unit testing annoying / infeasible.
