### ISSUE TITLE
MemoryError while reading nearly 1.8M rows of data from Bigquery table

### ISSUE THREAD

**Issue by HarshCHhz** [pydata/pandas-gbq#205]
Hi, while trying to fetch the data of 1.8 M rows from Bigquery to local machine, we are getting Memory Error.

Import pandas_gbq as pgbq
df= pgbq.read_gbq(sql, dialect)

**Comment by max-sixty** [comment]
Thanks for posting the issue.

This is a known one - ref https://github.com/pydata/pandas-gbq/issues/133 & https://github.com/pydata/pandas-gbq/issues/167

You can try installing the latest master - it has a material improvement, even if not where we want it to be. Depending on the size of your rows, 1.8m is stretching the current implementation on a moderately sized machine, but within range

I'll close this as a dupe but please post back here / another issue if needed

**Comment by HarshCHhz** [comment]
@max-sixty  will this solve the memory error issue?

**Comment by max-sixty** [comment]
Upgrading to master will reduce the memory requirement, and so may solve the memory issue.

**Comment by HarshCHhz** [comment]
Can you explain me the term masters as I am rookie into the python
programming

**Comment by tswast** [comment]
I'm not sure on your use-case for getting a pandas DataFrame for a large BQ table, but if complex SQL is a problem, you may consider [Ibis](https://docs.ibis-project.org/) for aggregations. I've helped a bit on that project and [BigQuery support in Ibis is pretty solid](https://cloud.google.com/community/tutorials/bigquery-ibis). It's a pandas-like interface for constructing SQL.
