### ISSUE TITLE
`to_gbq` doesn't respect location argument when it also creates dataset

### ISSUE THREAD

**Issue by robertlacok** [pydata/pandas-gbq#213]
When trying to use the `to_gbq` method to both create dataset and the table, the method fails when setting the location other than `US`. 

The reason is that the location is not respected when creating dataset, so it defaults to `US`. However, trying to launch a LoadJob with `location='EU'` when the dataset is in the `US` leads to failure.

Steps to reproduce: 
```
to_gbq(df, 'my_dataset.my_table', google_cloud_project, location='EU')
```
where `my_dataset` doesn't exist. 

I can try fixing it by passing the `location` argument down to constructors of `_Table` and `_Dataset`, and then [here](https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/gbq.py#L1133) in the `create` method of `_Dataset` doing something like:
```
if self.location is not None:
    dataset.location = self.location
```

If you OK it I will test and submit a PR. Is there a better way?

**Comment by max-sixty** [comment]
Thanks for the report and diagnosis @robertlacok

@tswast - what do you think about a) a function arg b) part of the config c) part of the class you recently added?

**Comment by tswast** [comment]
We've already got the function argument for location 😄 (added in https://github.com/pydata/pandas-gbq/issues/177). I think it's more a matter of plumbing it through to the dataset constructor.

@robertlacok Yes, PRs welcome!
