### ISSUE TITLE
Allow partial schemas in to_gbq() table_schema

### ISSUE THREAD

**Issue by melissachang** [pydata/pandas-gbq#218]
I am using pandas with BigQuery tables. Because pandas doesn't support boolean missing values, BigQuery BOOLEAN columns become dataframe object columns. I have to use to_gbq() table_schema to convert force those columns back to BOOLEAN.

My dataframe has 62 columns. table_schema has to include every column. It would be nice if I could only pass in the boolean columns in table_schema; for the other columns, to_gbq should default to dataframe column type.

**Comment by tswast** [comment]
Currently, if not all columns are specified in the `table_schema`, you get an error, correct? I think it's reasonable to allow specifying a subset and treating them as overrides, leaving the others unchanged.

**Comment by melissachang** [comment]
Yes, if not all columns are specified, you get an error.

For completeness, I want column order to be preserved. Eg say my df has columns A, B, C, D, E. I pass in table schema with C. I want output BigQuery table to have column order A, B, C, D, E.

**Comment by tswast** [comment]
Closed by https://github.com/pydata/pandas-gbq/pull/257
