### ISSUE TITLE
Context class (new in 0.7.0) is not thread-safe

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#221]
It's possible that someone is calling `read_gbq` from multiple threads. With the current implementation of `Context`, such code may break because we do not protect the cached credentials / project properties with a mutex.

**Comment by max-sixty** [comment]
But wouldn't both threads be writing the same data (the result of `auth.get_credentials`), so there's no data race?

**Comment by tswast** [comment]
I think `auth.get_credentials()` could return two different refresh tokens, but since either credential is interchangeable effectively it's the same. I didn't realize that [assignment is atomic in Python](https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe), so that makes me a lot less concerned.

It sounds like we might encounter some clobbering when refreshing tokens but maybe rarely? https://github.com/GoogleCloudPlatform/google-auth-library-python/issues/246 If we encounter that, then it's probably worth raising another issue in google-auth rather than working around it here.

**Comment by max-sixty** [comment]
Great. Yes; with limited power comes limited responsibility
