### ISSUE TITLE
Feature Request: Requesting support for streaming data to bigquery

### ISSUE THREAD

**Issue by rahul1990gupta** [pydata/pandas-gbq#238]
to_gbq() method can only to be called at most 1000 times before it gets the `quota exceeded` error
https://cloud.google.com/bigquery/quotas

It would be nice to have a support for stream data to big-query where writing to big-query table is implemented by client.insert_rows method as described below in the link.

https://cloud.google.com/bigquery/streaming-data-into-bigquery#bigquery-stream-data-python

System details:
Ubuntu 14.04
pandas                             0.22.0             
pandas-gbq                         0.7.0

**Comment by max-sixty** [comment]
Thanks for the issue @rahul1990gupta 

While I think we'd take a PR for this, I don't think it's a good pattern - streaming is slower and more expensive than batch loads, and that we're only loading data from pandas means the data has already been aggregated to some extent. 

I hear you re the 1000 limit, but can you find workarounds - e.g. can you aggregate your data and upload in fewer larger batches? Or if you're a heavy user of BQ, you may be able to have the limit increased if you ask Google support.

**Comment by tswast** [comment]
+1 to workarounds if at all possible.

Are you creating >1000 tables per day or are these dataframes appending/replacing existing tables. My biggest hesitation with allowing streaming as an option is that replacing a table using streaming is very flakey. We'd have to re-add logic to wait 2 minutes between deleting at table and writing rows to it when replacing a table, which I don't think is a very good user experience in the general case.

**Comment by tswast** [comment]
If you absolutely must do streaming, note that the pandas-gbq library builds on the google-cloud-bigquery library, which does have a streaming method [insert_rows()](https://googleapis.github.io/google-cloud-python/latest/bigquery/generated/google.cloud.bigquery.client.Client.html#google.cloud.bigquery.client.Client.insert_rows)

[Get a list of rows from the dataframe](https://stackoverflow.com/a/31324373) and [use the "grouper" example from itertools](https://docs.python.org/3.7/library/itertools.html) to collect into reasonable-sized batches. Call `bqclient.insert_rows(batch)` for each batch of rows.

**Comment by tswast** [comment]
Unlike `to_gbq`, `bqclient.insert_rows` does require

**Comment by tswast** [comment]
Unlike `to_gbq`, `bqclient.insert_rows` does require a table to exist, so if you're creating 1000s of new tables per day, this is a little more complicated. There's an internal [pandas_gbq.gbq.generate_bq_schema](https://github.com/pydata/pandas-gbq/blob/398e75e0d26651448f5d74c0684ad2ed8a3a05d1/pandas_gbq/gbq.py#L1040) method, which may help with creating tables.

**Comment by tswast** [comment]
Closing this issue as out-of-scope for the pandas-gbq library.

**Comment by tswast** [comment]
@rahul1990gupta I've thought more about this feature request, and I believe it's an appropriate addition to the `google-cloud-bigquery` library but not `pandas-gbq`. I've filed https://github.com/googleapis/google-cloud-python/issues/7553 to track adding a `insert_rows_from_dataframe` method there.
