### ISSUE TITLE
BytesIO buffers remain open after being written

### ISSUE THREAD

**Issue by bsolomon1124** [pydata/pandas-gbq#244]
While they will eventually be destroyed and [closed](https://docs.python.org/3.7/tutorial/inputoutput.html#reading-and-writing-files) by the garbage collector, it is generally good practice to close file objects via either using them as a `with` context manager or explicitly calling `f.close()`.

In `pandas_gbq/load.py`, it looks like the `chunk_buffer`(s) remain open after being written to GBQ.  Is there a reason for them to be left open, or would it be sounder practice to call `.close()` on them in a `finally` block?

Here is an example that seems to confirm.  (I suspected they might be closed by the underlying function call from google-cloud Python library itself, but that does not look to be true, unless I am missing something.)

First I threw in a few print statements to `load.py`:

```python
    chunks = encode_chunks(dataframe, chunksize=chunksize)
    for remaining_rows, chunk_buffer in chunks:
        try:
            yield remaining_rows
            client.load_table_from_file(
                chunk_buffer,
                destination_table,
                job_config=job_config,
                location=location,
            ).result()
        finally:
            print("Chunk buffer:", chunk_buffer, id(chunk_buffer))
            print("Closed:", chunk_buffer.closed)
            print()
```

The result:

```python
>>> from google.oauth2.service_account import Credentials 
>>> import pandas.util.testing as tm
>>> from pandas_gbq import to_gbq
>>> 
>>> df = tm.makeDataFrame()
>>> 
>>> to_gbq(
...     dataframe=df,
...     destination_table='aaa.bbb',
...     project_id='xyz',
...     if_exists='append',
...     progress_bar=False,
...     credentials=Credentials.from_service_account_file('xxx...a111.json')
... )
Chunk buffer: <_io.BytesIO object at 0x110864f10> 4572204816
Closed: False  # < -- Uh oh
```

The relevant code is in [`load.py`](https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/load.py), where `encode_chunk()` returns an open `BytesIO` object that is funneled through a generator and then uploaded via `client.load_table_from_file()`.

I would propose something like:

```python
    chunks = encode_chunks(dataframe, chunksize=chunksize)
    for remaining_rows, chunk_buffer in chunks:
        try:
            yield remaining_rows
            client.load_table_from_file(
                chunk_buffer,
                destination_table,
                job_config=job_config,
                location=location,
            ).result()
        finally:
            chunk_buffer.close()
```

----

My info: Python 3.7.2, pandas_gbq 0.9.0

**Comment by max-sixty** [comment]
Thanks for the report @bsolomon1124 

I think we'd take a PR for this. 

I _think_ that if we didn't return the buffer, then CPython would ref count that down and collect it, because it wouldn't be in scope any longer

**Comment by bsolomon1124** [comment]
@max-sixty thanks for taking a look - wanted to bring it up here and stress-test my assumptions before submitting a PR.

I'm not well-versed enough to know exactly when CPython (and it will also vary by implementation) would actually collect it, but I know that even if the opening happens in a local scope, that still sets this dunder attribute which doesn't seem ideal to me, naively speaking:

```python
>>> def g() -> None:
...     open('/tmp/file.tmp', 'w')
... 
>>> g()
>>> from pprint import pprint
>>> pprint(__warningregistry__)
{'version': 0,
 ("unclosed file <_io.TextIOWrapper name='/tmp/file.tmp' mode='w' encoding='UTF-8'>", <class 'ResourceWarning'>, 2): True}
```
