### ISSUE TITLE
Use google-auth library and requests instead of google-api-client

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#26]
The [google-auth](https://google-auth.readthedocs.io/en/latest/) library provides a Requests interface.

The google-auth library is preferred over the oauth2client library.

Would this project be amenable to a PR to update how the requests to BigQuery are made?

**Comment by MaximilianR** [comment]
My working hypothesis is we should transition to the `google.cloud.bigquery` library over time, and that library can wrap any auth calls. 

But I'm not a maintainer, and I may be missing something - is there a reason we would need to auth separately from that library?

**Comment by tswast** [comment]
Yeah `google.cloud.bigquery` would be okay, but since we only need the query feature it might be overkill. Also, `google-auth` is 1.0, but `google.cloud.bigquery` is still going through breaking changes.

**Comment by jreback** [comment]
how much work would be involved to accept this an alternative? iow you try to import oauth2client if that fails you can this package else give up

**Comment by parthea** [comment]
I'm happy to help with testing/code review for this feature.

**Comment by parthea** [comment]
> how much work would be involved to accept this an alternative? iow you try to import oauth2client if that fails you can this package else give up

This sounds great ( or vise-versa, if  google-auth , else if  oauth2client else give up)

**Comment by tswast** [comment]
What's the reason for accepting either library?

**Comment by parthea** [comment]
> What's the reason for accepting either library?

@tswast I see your point. Assuming that we can maintain the existing functionality of `pandas-gbq` with `google-auth`, then I agree we could drop `oauth2client`. @jreback , would that be ok?

Note: Historically, `oauth2client` was an [optional dependency](http://pandas.pydata.org/pandas-docs/stable/install.html#install-optional-dependencies) for `pandas` so we had to deal with the scenario where users did not have certain libraries. Now that we have migrated `pandas.io.gbq` to `pandas-gbq` as a separate package from `pandas` we have more control over the dependencies.

**Comment by jreback** [comment]
ok with changing dependencies. Though nice to have some back-compat. IOW I ok just adding this library, then deprecating the old.

**Comment by MaximilianR** [comment]
You guys know this better, but is it worth considering `google.cloud.bigquery`? 

We have built a set of internal functions on this (which we're planning to move into this library). It takes care of a lot of the boilerplate. 

Is there a compelling reason not to add this as a dependency?

**Comment by jreback** [comment]
thats #25; again which am happy to take, assuming things can be built/installed/tested properly.

**Comment by MaximilianR** [comment]
> thats #25; again which am happy to take, assuming things can be built/installed/tested properly.

Then I think we can also use that library for auth (I believe it wraps `google-auth`), and this discussion would be moot.

I commented [here](https://github.com/pydata/pandas-gbq/pull/25#discussion_r112318991); we can still use json keys with either the `oauth2client` or `google-auth` if we want to enable that

**Comment by tswast** [comment]
I'll close this out in favor of eventually moving the API-calling code to google-cloud-python. I've got a separate PR open to move to the new auth library without changing the client libraries.

The queries wouldn't be too bad to do with a pure REST call, but the file uploads get a bit hairy, so having a library help with that is ideal.
