### ISSUE TITLE
Empty upload raises ZeroDivisionError at gbq.py", line 524, in load_data

### ISSUE THREAD

**Issue by vackosar** [pydata/pandas-gbq#260]
```pd.DataFrame(columns=['a', 'b']).to_gbq(...)```
creates table but raises ZeroDivisionError at gbq.py", line 524, in load_data

**Comment by vackosar** [comment]
it seems that it is already fixed on master branch

**Comment by max-sixty** [comment]
Yes, thanks for the issue @vackosar . I'll close for now given there's a fix, but please reopen if you hit any other issues.
