### ISSUE TITLE
CLN: Plan to drop Python 2 support

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#268]
As discovered in https://github.com/pydata/pandas-gbq/pull/254 for #253, pandas 0.25.0 is starting to drop compatibility functions for Python 2 support.

Since this package is pretty tightly coupled with upstream pandas, we'll need to follow-suit soon. Perhaps 0.10.0 is the last version that we officially support Python 2? I'd like to make sure we are able to run our test suite against 0.25.x, and supporting Python 2 is potentially a blocker.

**Comment by max-sixty** [comment]
Definitely up for dropping Py2! I think we could drop the support and package metadata fairly soon. 0.10.0 sounds very reasonable.
