### ISSUE TITLE
DOC: Improve the documentation for running integration tests locally

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#27]
I'd love to see a TESTING.md file that showed how to run the tests locally before sending off a PR.

I can run `pytest` but is that running the integration tests, too? It seemed to run a bit fast for that to be the case.

**Comment by jreback** [comment]
http://pandas-gbq.readthedocs.io/en/latest/contributing.html

is pretty comprehensive

**Comment by jreback** [comment]
of course if u think it needs updates then pls send a PR

**Comment by parthea** [comment]
I set the following when running integration tests locally: 

```
PROJECT_ID = None
PRIVATE_KEY_JSON_PATH = None
PRIVATE_KEY_JSON_CONTENTS = None
```

I scanned through the contributing docs and it appears that this step is missing (it wasn't in the `pandas` contributing docs either). I'll re-open this issue so we can update the docs.

https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/tests/test_gbq.py#L22

**Comment by parthea** [comment]
@tswast The integration tests are skipped if you do not provide credentials/project id . I'm open to improving the local integration testing process as well. Some users may not want to use their default gcloud credentials to run `pandas-gbq` integration tests but another alternative could be to use environment variables, or have a separate file for `PROJECT_ID`, `PRIVATE_KEY_JSON_PATH` and `PRIVATE_KEY_JSON_CONTENTS` . Thoughts?

**Comment by tswast** [comment]
That makes sense to skip, even if default gcloud credentials are available. I'll try running through the current workflow this morning to see how it goes.

**Comment by tswast** [comment]
Question: Does it make any sense to populate PRIVATE_KEY_JSON_PATH but not PRIVATE_KEY_JSON_CONTENTS?

I'm thinking of always loading the contents of the key file in `_get_private_key_contents`.

**Comment by parthea** [comment]
@tswast You're right. It seems redundant to have `PRIVATE_KEY_JSON_CONTENTS` in `test_gbq.py` since we could read Json from the file in `PRIVATE_KEY_JSON_PATH`.
