### ISSUE TITLE
ENH: Add user-agent string when constructing BigQuery and BigQuery Storage API clients.

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#281]
It would help me prioritize work on pandas-gbq if Google could see how much BigQuery usage originates from pandas-gbq. Plus, it's actually required by the Google APIs terms of service that we accurately identify our "application" accurately in requests to Google APIs.

To do this, we need to populate the `user_agent` property of [`google.api_core.client_info.ClientInfo`](https://googleapis.github.io/google-cloud-python/latest/core/client_info.html#google.api_core.client_info.ClientInfo) or [`google.api_core.gapic_v1.client_info.ClientInfo`](https://googleapis.github.io/google-cloud-python/latest/core/client_info.html#google.api_core.gapic_v1.client_info.ClientInfo) when we construct a `bigquery.Client` or `bigquery_storage_v1beta1.Client`, respectively.

I propose we use the pandas version information in this string, as pandas seems to be the "application", since this package exists to ith `pandas.read_gbq`.

```
bigquery.Client(
    client_info=ClientInfo(
        user_agent="pandas-{}".format(get the pandas version)
    )
)
```

Related: https://github.com/googleapis/google-cloud-python/issues/8696

**Comment by dkapitan** [comment]
Makes perfect sense.
