### ISSUE TITLE
Is it possible to export data to BigQuery arrays with `to_gbq`?

### ISSUE THREAD

**Issue by mtchllbrrn** [pydata/pandas-gbq#289]
I'm trying to export a DataFrame to BigQuery with `to_gbq`, and a few columns have array values.  Unfortunately, these get coerced into strings if I rely on the built-in schema inference.  If I manually specify `ARRAY` type in `table_schema` I get this error: "Invalid value for type: ARRAY is not a valid value."

I see that ARRAY is not listed as a valid type [here](https://pandas-gbq.readthedocs.io/en/latest/writing.html?highlight=schema#inferring-the-table-schema), but I'm having trouble finding any further documentation.  Is this not supported?

**Comment by max-sixty** [comment]
There's very limited support given pandas' support for nested arrays. @tswast will know better but one reasonable approach is to convert to a better supported format (unnest / another table / string), and then normalize into arrays with a BQ query over your uploaded data

**Comment by dkapitan** [comment]
@mtchllbrrn 
Good question, I don't think this is possible. Under the hood, `to_gbq` uses standard GBQ client with CSV as an intermediate format. Repeated fields are not supported for this ingestion format, see https://cloud.google.com/bigquery/docs/loading-data-cloud-storage-csv#limitations.

**Comment by mtchllbrrn** [comment]
Got it, thanks for the help y'all.  I'll plan on exporting as strings and converting to arrays with a BQ query.
