### ISSUE TITLE
AttributeError when use_bqstorage_api=True on empty df

### ISSUE THREAD

**Issue by Bizetremi** [pydata/pandas-gbq#299]
The following error is thrown when using pandas_gbq.read_gbq with use_bqstorage_api=True when the query returns no data.

  (use_bqstorage_api=True)
  File '/env/local/lib/python3.7/site-packages/pandas_gbq/gbq.py', line 1034, in read_gbq
    progress_bar_type=progress_bar_type,
  File '/env/local/lib/python3.7/site-packages/pandas_gbq/gbq.py', line 532, in run_query
    progress_bar_type=progress_bar_type,
  File '/env/local/lib/python3.7/site-packages/pandas_gbq/gbq.py', line 576, in _download_results
    df = _localize_df(schema_fields, df)
  File '/env/local/lib/python3.7/site-packages/pandas_gbq/gbq.py', line 808, in _localize_df
    if field['type'].upper() == 'TIMESTAMP' and df[column].dt.tz is None:
  File '/env/local/lib/python3.7/site-packages/pandas/core/generic.py', line 5175, in __getattr__
    return object.__getattribute__(self, name)
  File '/env/local/lib/python3.7/site-packages/pandas/core/accessor.py', line 175, in __get__
    accessor_obj = self._accessor(obj)
  File '/env/local/lib/python3.7/site-packages/pandas/core/indexes/accessors.py', line 343, in __new__
    raise AttributeError('Can only use .dt accessor with datetimelike ' 'values')
AttributeError: Can only use .dt accessor with datetimelike values

**Comment by tswast** [comment]
I'm not able to reproduce with a plain empty result set. This test passes:

```python
def test_empty_results(method_under_test):
    """Test with an empty dataframe.

    See: https://github.com/pydata/pandas-gbq/issues/299
    """
    df = method_under_test(
        "SELECT * FROM (SELECT 1) AS tbl WHERE TRUE = FALSE;",
        use_bqstorage_api=True,
    )
    assert len(df.index) == 0
```

Based on the stacktrace, I'll try a query where a timestamp column is in the results.

**Comment by tswast** [comment]
> Based on the stacktrace, I'll try a query where a timestamp column is in the results.

Confirmed. The test fails with the query `"SELECT * FROM (SELECT TIMESTAMP('2020-02-11 16:33:32-06:00')) WHERE TRUE = FALSE;"`.
