### ISSUE TITLE
Split LICENSE file into separate LICENSE and AUTHORS files.

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#30]
The [GitHub robot (Ruby Licenseee Gem)](https://help.github.com/articles/licensing-a-repository/#detecting-a-license) isn't properly detecting the license as BSD simplified.

Seems to me that the **About the Copyright Holders** and **Our Copyright Policy** sections could be pulled into an AUTHORS.md file. The LICENSE file could then be the generic BSD license, which is more easily detected by scrapers such as GitHub's logic.

**Comment by parthea** [comment]
cc @jreback

**Comment by jreback** [comment]
you could do this

the license was just copied directly from pandas (so could submit a pr there as well)
