### ISSUE TITLE
ENH: restrict to Python 3.5 and higher in setup.py

### ISSUE THREAD

**Issue by nicoa** [pydata/pandas-gbq#306]
Some Foreword: please ask me for further information/MWE if necessary, I hope it will be understandable without for now:

We expercienced some error like the following:
```
MYENV/local/lib/python2.7/site-packages/pandas/io/common.pyc in writerows(self, rows)
    549             data = self.encoder.encode(data)
    550             # write to the target stream
--> 551             self.stream.write(data)
    552             # empty queue
    553             self.queue.truncate(0)

TypeError: unicode argument expected, got 'str'
```

This seems to appear in version 0.13.0, pinning back to 0.12.0 seems to work.

Still, referring to the changelog they are both not supported under python 2 (under which this occurred). Is it expected behaviour they get still installed? Is this a problem on pypi side or can it be fixed on the package site?

Thanks for your efforts!

**Comment by tswast** [comment]
I thought that removing Python 2 from the classifiers and removing the "universal" mark in the manifest would be sufficient (https://github.com/pydata/pandas-gbq/pull/273) but maybe there's something else we need to do?

**Comment by tswast** [comment]
What commands are you using to install the package?

**Comment by nicoa** [comment]
Regarding the commands used: I'm not sure since with no access to it right now, but with rather high probability we install this from a requirements file to some virtualenv using pip. Will update later these days as soon as having access again.

**Comment by tswast** [comment]
Looks like there's a `python_requires` we can add to `setup.py`. https://stackoverflow.com/a/45362425/101923

I believe we support Python 3.5 and higher.
