### ISSUE TITLE
Escaped query params for `read_gbq`

### ISSUE THREAD

**Issue by acarl005** [pydata/pandas-gbq#307]
Is there a way to use [parameterized queries](https://cloud.google.com/bigquery/docs/parameterized-queries) so that the parameters are scrubbed for potential malicious input?

**Comment by tswast** [comment]
You'll need to use the `configuration` argument to [read_gbq](https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq) which accepts a REST API job resource. See: https://cloud.google.com/bigquery/docs/reference/rest/v2/Job#JobConfiguration for details.

It'll be something like:

```python
configuration = {
    "query": {
        "queryParameters": [
            {
                "name": "user_entered_string",
                "parameterType": "STRING",
                "parameterValue": "Robert'); DROP TABLE Students;"
        ]
    }
}
```
