### ISSUE TITLE
Missing license headers

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#31]
Related to https://github.com/pydata/pandas-gbq/issues/30, the LICENSE file has a header that is supposed to be used on the code files, but I'm not seeing that.

**Comment by parthea** [comment]
@jreback Thoughts? I also noticed that **pandas-dev/pandas** does not have a license header on each code file. It is common to see license headers on each code file in Google's open source projects (For example,  **GoogleCloudPlatform/google-cloud-python** does this).

**Comment by jreback** [comment]
our code files have been around for quite a long time

we normally don't add code headers

**Comment by parthea** [comment]
@jreback Ok, closing this off. We can re-open if needed.
