### ISSUE TITLE
CLN: avoid use of `client.dataset`, prefer `DatasetReference` constructor, instead

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#312]
Getting deprecation warnings in integration tests:

```
samples/tests/test_to_gbq.py::test_to_gbq_simple
  /root/project/pandas_gbq/load.py:59: PendingDeprecationWarning: Client.dataset is deprecated and will be removed in a future version. Use a string like 'my_project.my_dataset' or a cloud.google.bigquery.DatasetReference object, instead.
    destination_table = client.dataset(dataset_id).table(table_id)
```

**Comment by nathan-ok** [comment]
A comment i found within the client.py class in the dataset function relating to this issue,
           As of ``google-cloud-bigquery`` version 1.7.0, all client methods
           that take a
           :class:`~google.cloud.bigquery.dataset.DatasetReference` or
           :class:`~google.cloud.bigquery.table.TableReference` also take a
           string in standard SQL format, e.g. ``project.dataset_id`` or
           ``project.dataset_id.table_id``.
https://cloud.google.com/bigquery/docs/reference/rest/v2/datasets#datasetreference
https://cloud.google.com/bigquery/docs/reference/rest/v2/tables#tablereference
