### ISSUE TITLE
Clarification on how this relates to pandas.io.gbq

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#32]
I see that `pandas.io.gbq` is [still in the Pandas master branch](https://github.com/pandas-dev/pandas/blob/844013b20c2a6230b1baeec1d5442e26b7930656/pandas/io/gbq.py).

Is there criteria for when that will get removed in favor of this package?

**Comment by jreback** [comment]
no its not. look closer. That is just an external interface.

**Comment by jreback** [comment]
https://github.com/pandas-dev/pandas/blob/844013b20c2a6230b1baeec1d5442e26b7930656/pandas/io/gbq.py#L94

**Comment by jreback** [comment]
This *does* use ``pandas-gbq`` directly.

**Comment by tswast** [comment]
Ah, thanks. Sorry I should have been able to figure that out.
