### ISSUE TITLE
Drop Python 3.5 and 3.6 support

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#337]
Pandas has already dropped 3.5 support: https://github.com/pandas-dev/pandas/issues/29034

This would allow us to use f-strings among other features.

**Comment by tswast** [comment]
For reference: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

3.6 support was also dropped. https://github.com/pandas-dev/pandas/pull/35214

**Comment by max-sixty** [comment]
👍
