### ISSUE TITLE
to_gbq Error Converting np.float64/np.float32 To NUMERIC

### ISSUE THREAD

**Issue by HomelessSandwich** [pydata/pandas-gbq#351]
Hi,

I am using these versions of Python and libraries:
> Python: 3.7.7
> Pandas: 1.1.0
> Numpy: 1.18.5
> pandas_gbq: 0.14.1

I am attempting to write to the following table with this schema:
| Field name | Type      | Mode     |
|------------|-----------|----------|
| created_at | TIMESTAMP | REQUIRED |
| symbol     | STRING    | REQUIRED |
| open       | NUMERIC   | NULLABLE |
| high       | NUMERIC   | NULLABLE |
| low        | NUMERIC   | NULLABLE |
| close      | NUMERIC   | NULLABLE |
| adj_close  | NUMERIC   | NULLABLE |
| volume     | NUMERIC   | NULLABLE |

When using:
```python
table_schema = [
    {'name': 'created_at', 'type': 'TIMESTAMP'},
    {'name': 'symbol', 'type': 'STRING'},
    {'name': 'open', 'type': 'NUMERIC'},
    {'name': 'high', 'type': 'NUMERIC'},
    {'name': 'low', 'type': 'NUMERIC'},
    {'name': 'close', 'type': 'NUMERIC'},
    {'name': 'adj_close', 'type': 'NUMERIC'},
    {'name': 'volume', 'type': 'NUMERIC'}
]

df.to_gbq(
        destination_table=f'{dataset}.{table}',
        project_id=project,
        if_exists='append',
        table_schema=table_schema,
        chunksize=10000
)
```

I get the following error:
```python
GenericGBQException: Reason: 400 Error while reading data, error message: Could not parse '2.3399999141693115' as NUMERIC for field open (position 1) starting at location 103164  with message 'Invalid NUMERIC value: 2.3399999141693115'
```

I have tried using `np.float64` and `np.float32` dtypes, but I get the same error. Using integer values does work however. I would like to avoid converting to a rounding/string as it's a bit too computationally expensive. I am unsure how to resolve this. Any help would be greatly appreciated!

**Comment by max-sixty** [comment]
I'm not sure how this would work, as pandas doesn't have a numeric type.

Probably the closest approach is to load into another table and do the conversion in BQ.

**Comment by HomelessSandwich** [comment]
Ok, I'll use a `FLOAT64` in the table schema then. Thanks for the help!
Are there any plans to get a `NUMERIC` data type to work with this?
For me, I would prefer to use `NUMERIC` over `FLOAT64` in the table schema.

**Comment by max-sixty** [comment]
OK sounds good.

Using numeric types in this library relies on them being available in pandas; I don't know of any plans to do that, though would welcome it...
