### ISSUE TITLE
0.15.0: `cannot import name '_check_google_client_version' from 'pandas_gbq.gbq'`

### ISSUE THREAD

**Issue by tianjianjiang** [pydata/pandas-gbq#360]
<img width="640" alt="Airflow_-_DAGs_-_Vivaldi" src="https://user-images.githubusercontent.com/4812544/113234317-03413e80-92dc-11eb-8f50-aec8e72086f5.png">

Versions of related packages inside the webserver container:
```bash
airflow@cfaac0843862:~$ pip freeze | grep pandas-gbq
 pandas-gbq==0.15.0
airflow@cfaac0843862:~$ pip freeze | grep google-cloud-bigquery
 google-cloud-bigquery==2.13.1
 google-cloud-bigquery-storage==2.3.0
```

**Comment by Yinabled** [comment]
I'm running into this issue as well with `pandas_gbq` using `BigQueryHook` in Airflow.

**Comment by max-sixty** [comment]
Do you have a fuller stack trace? That attribute is not in [v0.15.0's gbq.py](https://github.com/pydata/pandas-gbq/blob/0.15.0/pandas_gbq/gbq.py). What is attempting to import that? It may be another library.

**Comment by tianjianjiang** [comment]
Hi @max-sixty ,
Sorry I didn't put that stack trace in the first place (because it was basically just an import).
As @Yinabled aforementioned, that call happens at
https://github.com/apache/airflow/blob/1.10.15/airflow/contrib/hooks/bigquery_hook.py#L39 as
```python
from pandas_gbq.gbq import \
    _check_google_client_version as gbq_check_google_client_version
```

**Comment by max-sixty** [comment]
OK — this is an issue for airflow, then. That's a private function; they need to either vendor it or use a public function.
