### ISSUE TITLE
Python unit test failing with ImportError: cannot import name '_check_google_client_version' from 'pandas_gbq.gbq'

### ISSUE THREAD

**Issue by chandu-007** [pydata/pandas-gbq#361]
when we run the unit test on airflow dag it is failing with ImportError: cannot import name '_check_google_client_version' from 'pandas_gbq.gbq'. i was working fine till 31/03/2021. From 01/04/2021 we are facing this issue.

**Unittest file code:**

import unittest
from airflow.models import DagBag

class TestDags(unittest.TestCase):

    LOAD_THRESHOLD_SECONDS = 2

    def setUp(self):
        self.dagbag = DagBag()

    def test_dags_syntax(self):
        for key in self.dagbag.dags.keys():
            print(key)
        self.assertFalse(
            len(self.dagbag.import_errors),
            f"DAG import errors. Errors: {self.dagbag.import_errors}"
        )

if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(TestDags)
    unittest.TextTestRunner(verbosity=2).run(suite)

**Full Error Log:-**

Step #2 - "Test": ImportError: cannot import name '_check_google_client_version' from 'pandas_gbq.gbq' (/usr/local/lib/python3.7/site-packages/pandas_gbq/gbq.py)
Step #2 - "Test": [2021-04-01 05:59:36,804] {dagbag.py:239} ERROR - Failed to import: /workspace/dags/CVMRPT/DAG_CVMRPT_Z3_D1_SNIPER_ANALYSIS_20.py
Step #2 - "Test": Traceback (most recent call last):
Step #2 - "Test":   File "/usr/local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 236, in process_file
Step #2 - "Test":     m = imp.load_source(mod_name, filepath)
Step #2 - "Test":   File "/usr/local/lib/python3.7/imp.py", line 171, in load_source
Step #2 - "Test":     module = _load(spec)
Step #2 - "Test":   File "<frozen importlib._bootstrap>", line 696, in _load
Step #2 - "Test":   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Step #2 - "Test":   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Step #2 - "Test":   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Step #2 - "Test":   File "/workspace/dags/CVMRPT/DAG_CVMRPT_Z3_D1_SNIPER_ANALYSIS_20.py", line 1, in <module>
Step #2 - "Test":     from airflow.contrib.operators.bigquery_operator import BigQueryOperator
Step #2 - "Test":   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/operators/bigquery_operator.py", line 26, in <module>
Step #2 - "Test":     from airflow.contrib.hooks.bigquery_hook import BigQueryHook
Step #2 - "Test":   File "/usr/local/lib/python3.7/site-packages/airflow/contrib/hooks/bigquery_hook.py", line 39, in <module>
Step #2 - "Test":     from pandas_gbq.gbq import \

**Comment by max-sixty** [comment]
dupe https://github.com/pydata/pandas-gbq/issues/360
