### ISSUE TITLE
Replace oauth2client by google-auth

### ISSUE THREAD

**Issue by ktong** [pydata/pandas-gbq#37]
oauth2client is now deprecated. No more features will be added to the libraries and the core team is turning down support. We recommend you use google-auth and oauthlib.

**Comment by tswast** [comment]
I believe the latest versions of `google-api-python-client` support google-auth, so this package should be able to do this with only some changes to setup.py.

**Comment by ktong** [comment]
It also need change the way to get application default credentials
```
try:
            from oauth2client.client import GoogleCredentials
        except ImportError:
            return None

        try:
            credentials = GoogleCredentials.get_application_default()
        except:
            return None
```

**Comment by ktong** [comment]
the new function is google.auth.default()

**Comment by tswast** [comment]
I started on this in https://github.com/tswast/pandas-gbq/tree/gbq-37. It uses google-auth for service accounts and application default credentials. I'll update it to use google-auth for user credentials tomorrow.
