### ISSUE TITLE
Provide a way to override requested scopes

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#38]
Additional scopes are required when using [BigQuery to access external data sources](https://cloud.google.com/bigquery/external-data-sources) such as Google Drive or Bigtable.

It looks like the `GbqConnector` class currently only uses the `https://www.googleapis.com/auth/bigquery` scope and does not override the scopes in the constructor.

**Comment by mremes** [comment]
Well, it's not Pandas-GoogleBigQuery package then anymore. Bigtable API has very different schema, and for drive I cannot see any general use case for getting data to a pandas DF.

**Comment by tswast** [comment]
@mremes You can query those data sources using the BigQuery API, you just need to create an external data source in BigQuery and have the right scopes.

**Comment by mremes** [comment]
Yup, sorry my bad! :)

**Comment by LauraRichter** [comment]
Hi. I'm having this same issue. I'e created an external bq data source that links to a google sheet. But reading it in with pd.read_gbq gives "BigQuery BigQuery: No OAuth token with Google Drive scope was found."
If not in pandas_gbq, where should the drive scope be set? Or are you saying that pandas_gbq shouldn't be used for this at all?

**Comment by tswast** [comment]
Pandas-GBQ does not yet support scopes other than BigQuery. If someone were to work on this feature request, there are several ways credentials can be fetched, so there are several places to update.

- Application Default Credentials
  
  https://github.com/pydata/pandas-gbq/blob/79c90677860d793626344aada7315ab6727b45aa/pandas_gbq/gbq.py#L251
- User credentials
  
  https://github.com/pydata/pandas-gbq/blob/79c90677860d793626344aada7315ab6727b45aa/pandas_gbq/gbq.py#L356
- Service account credentials
  
  https://github.com/pydata/pandas-gbq/blob/79c90677860d793626344aada7315ab6727b45aa/pandas_gbq/gbq.py#L393

**Comment by tswast** [comment]
I have accounted for this feedback in my auth proposal at https://github.com/pydata/pandas-gbq/issues/161.

I hope to add a new `pandas_gbq.get_user_credentials()` function which takes a `scopes` argument. Closing this issue as a duplicate of #161.
