### ISSUE TITLE
with BIGINT OverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by arita37** [pydata/pandas-gbq#42]
When doing a query with BIGINT Google, we get this message:

with BIGINT OverflowError: Python int too large to convert to C long

account_id=5742796208078848

In pandas, we dont see this bug.

**Comment by jreback** [comment]
pls show an actual example

**Comment by MrinalJain17** [comment]
It is because of the 'DATE', since it is in the format YYYYMMDDHHMMSS, which is too large to be an int.

Try converting it to string by casting it in the SQL query itself.
SELECT CAST(DATE as STRING)

**Comment by max-sixty** [comment]
I'm attempting to clean up stale issues. 

I think this may be an upstream issue with dates, though if this is a `pandas-gbq` issue, please repost and I'll reopen.
