### ISSUE TITLE
Improve the user experience when Google credentials are expired or revoked

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#50]
I think the user experience could be improved when Google credentials are expired or revoked. I see that we have a `reauth` parameter in `read_gbq` and `to_gbq` but this will cause the authentication to run each time even if the credentials are valid to cater for the environment where there are multiple users. It may be helpful to also have the ability to automatically trigger authentication flow when credentials are expired or revoked.

https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/gbq.py#L771

**Comment by tswast** [comment]
This is partially addressed by https://github.com/pydata/pandas-gbq/pull/212. It's now possible to refresh the credentials if the credentials are expired or revoked by manually setting `reauth=True`. Before that change, pandas-gbq would still try to load the expired credentials even when `reauth=True` and would fail with this error.

**Comment by parthea** [comment]
Closing as obsolete.
