### ISSUE TITLE
TST: flake8 should run on all python builds

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#51]
From PR #39 , 
I received the following warning when running `flake8` on branch `tswast:gbq-37` but Travis did not report the warning. 

Local run:
```
tony@tonypc:~/pydata-pandas-gbq$ flake8 pandas_gbq 
pandas_gbq/tests/test_gbq.py:136:61: F841 local variable 'e' is assigned to but never used
```

On Travis:
https://travis-ci.org/tswast/pandas-gbq/jobs/234914390

**Comment by parthea** [comment]
Flake8 is currently only running on python 3.6 in the Travis environment, whereas my local environment is python 2.7.

**Comment by jreback** [comment]
just turn it on additionally for 2.7
