### ISSUE TITLE
TST: Potentially add a unit test to verify the functionality of parameter `auth_local_webserver`

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#53]
It may be possible to add a unit test to verify the functionality of parameter `auth_local_webserver` of `read_gbq()` and `to_gbq()` in #39 in order to improve testing. One potential solution is to capture the output in the unit test and look for specific text :

`'Go to the following link in your browser:'` , when `auth_local_webserver=False`
or
`'Your browser has been opened to visit:'` , when `auth_local_webserver=True`

**Comment by tswast** [comment]
This parameter is now passed on through to pydata-google-auth. I've filed this as https://github.com/pydata/pydata-google-auth/issues/9 over there.
