### ISSUE TITLE
TST: failing tests

### ISSUE THREAD

**Issue by jreback** [pydata/pandas-gbq#57]
seems our tests have been failing for a bit: https://travis-ci.org/pydata/pandas-gbq/builds/233574394

any ideas @parthea ?

**Comment by parthea** [comment]
@tswast has improved the reliability of integration tests in #39 (Thanks @tswast !) . I think the issue should be resolved once that PR is merged. See the test results of that branch here: https://travis-ci.org/parthea/pandas-gbq/builds/240416942

**Comment by jreback** [comment]
that's fine but why are the current ones failing?

**Comment by tswast** [comment]
Yeah, I addressed the "GenericGBQException: Reason: resourceInUse, Message: Dataset pandas-travis:pandas_gbq_867321 is still in use" errors in my PR.

The reason for the current test failures is that while dataset and table listing have always been eventually consistent, the latency increased slightly with a BigQuery backend release a couple weeks ago.
