### ISSUE TITLE
DOC: Add conda install steps for google-auth*

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#63]
From #62, we need to include steps in the pandas-gbq documentation on how to install the following:

```
google-auth
```
```
google-auth-httplib2
```
```
google-auth-oauthlib
```

**Comment by tswast** [comment]
I believe this should automatically be installed based on the dependencies listed at https://github.com/conda-forge/pandas-gbq-feedstock/blob/master/recipe/meta.yaml after we install the next version, but we should show this for when folks install the library in development mode: `pip install -e .` along with `conda develop`.
