### ISSUE TITLE
Bulk upload

### ISSUE THREAD

**Issue by maxim-lian** [pydata/pandas-gbq#7]
ref: https://github.com/pandas-dev/pandas/issues/14670

R does this well, and it makes a material performance impact

**Comment by MaximilianR** [comment]
I've got this working internally, by writing to a CSV and then uploading that.

I've used the `google.cloud.bigquery` library though, which this library doesn't seem to use. Is there an explicit reason for this? The credentials are handled a bit differently.

**Comment by jreback** [comment]
you could certainly add that as a dep. looks like that is a refactor of some older libs?

**Comment by MaximilianR** [comment]
OK

**Comment by jreback** [comment]
yeah looks like these are the 'new' ones: https://cloud.google.com/bigquery/docs/reference/libraries#client-libraries-usage-python

**Comment by tswast** [comment]
Fixed by https://github.com/pydata/pandas-gbq/pull/25. I'll update the changelog to link to this.

**Comment by melissachang** [comment]
What version of pandas will this be in? How do I find out?

**Comment by tswast** [comment]
@melissachang It is now in the released version of `pandas-gbq` 0.3.0. https://github.com/pydata/pandas-gbq/releases/tag/0.3.0
