### ISSUE TITLE
Integration tests should fail rather than skip if project id is not set in Travis

### ISSUE THREAD

**Issue by parthea** [pydata/pandas-gbq#72]
Certain integration tests are [skipped](https://github.com/pydata/pandas-gbq/blob/master/pandas_gbq/tests/test_gbq.py#L25) if a BigQuery project is not set in Travis. My initial thought is that the tests should fail if a BigQuery project id is not provided. 

For reference, here are the steps to run the BigQuery integration tests on Travis:
https://pandas-gbq.readthedocs.io/en/latest/contributing.html#running-google-bigquery-integration-tests

**Comment by max-sixty** [comment]
This was merged to master earlier this year, closing
