### ISSUE TITLE
RLS: 0.2.0

### ISSUE THREAD

**Issue by jreback** [pydata/pandas-gbq#74]
@parthea can you do this release?

whatsnew needs updating to the date of the release and otherwise follow the release-procedure.

also some things failing which :<

https://travis-ci.org/pydata/pandas-gbq/builds/256434923

**Comment by parthea** [comment]
Sure. I can try to make a release. 

I've opened a new issue to track the recent build failures. Note: This not a regression in `pandas-gbq` as the previous version of `pandas-gbq` also has this issue.

**Comment by parthea** [comment]
@jreback  I'm stuck at step  `twine upload dist/*` with error `HTTPError: 403 Client Error: Invalid or non-existent authentication information.` Do I need permissions to publish to pypi?

**Comment by jreback** [comment]
@parthea you should be good to go to upload to PyPi (then trigger conda-forge). pls check docs after as well.

Note that we want travis to be passing before releases. you can xfail these tests until they are fixed / worked around. These were very recently working. So it is odd.

**Comment by parthea** [comment]
I restarted the builds on travis and now the 0.2.0 release is passing https://travis-ci.org/pydata/pandas-gbq/builds/256746482 . I'll submit a separate PR to xfail the intermittent test while we look into issue #75.

I've published [0.2.0 on PyPi](https://pypi.python.org/pypi/pandas-gbq/0.2.0) and submitted a [pull request on conda-forge](https://github.com/conda-forge/pandas-gbq-feedstock/pull/6). Please take a look.

While reviewing the 0.2.0 docs, I noticed that the [change log](http://pandas-gbq.readthedocs.io/en/stable/changelog.html) in the docs has a formatting error which has been fixed on master in https://github.com/pydata/pandas-gbq/commit/0b25a6bb40bc0f4bba8a041d500ac8fd60f3eb90. Should I fix the formatting error in the docs for the 0.2.0 release, and delete and re-create the 0.2.0 tag?

**Comment by jreback** [comment]
just push a new commit to fix docs

you can NEVER change a release tag

**Comment by jreback** [comment]
thanks @parthea 

let's xfail those flakey tests until fixed.

**Comment by jreback** [comment]
if you want to send out a release note to the mailing this would be great (completely optional here), something like this: (and then put a link in the wiki): https://github.com/pandas-dev/pandas/wiki/Release-Checklist
