### ISSUE TITLE
Request payload size exceeds the limit: 10485760 bytes.

### ISSUE THREAD

**Issue by pkallos** [pydata/pandas-gbq#82]
I am writing a dataframe to pandas and have received this error:

`pandas_gbq.gbq.GenericGBQException: Reason: badRequest, Message: Request payload size exceeds the limit: 10485760 bytes`

Strangely I see the message that streaming insert was 100% complete:
```
Streaming Insert is 100% Complete

Traceback (most recent call last):
  File "...lib/python2.7/site-packages/pandas/core/frame.py", line 957, in to_gbq
    if_exists=if_exists, private_key=private_key)
  File "...lib/python2.7/site-packages/pandas/io/gbq.py", line 109, in to_gbq
    if_exists=if_exists, private_key=private_key)
  File "...lib/python2.7/site-packages/pandas_gbq/gbq.py", line 1056, in to_gbq
    connector.load_data(dataframe, dataset_id, table_id, chunksize)
  File "...lib/python2.7/site-packages/pandas_gbq/gbq.py", line 643, in load_data
    self.process_http_error(ex)
  File "...lib/python2.7/site-packages/pandas_gbq/gbq.py", line 454, in process_http_error
    "Reason: {0}, Message: {1}".format(reason, message))
pandas_gbq.gbq.GenericGBQException: Reason: badRequest, Message: Request payload size exceeds the limit: 10485760 bytes.
```

**Comment by MaximilianR** [comment]
What was the dataframe? Can you try setting the batch size to a lower value?

**Comment by pkallos** [comment]
The dataframe was about 200x2500 so pretty large, mostly Float values. Adjusting `chunksize=` down to `200` worked.

If someone with better working knowledge of pandas bgq can give me an indication of whether its practical, I might be able to open a PR that automatically limits the chunksize in cases where the payload is too large?

**Comment by tswast** [comment]
I’m closing this issue as the latest version of pandas-gbq uses load jobs instead of streaming to upload data.
