### ISSUE TITLE
Keeps asking for authentication when running as a cron job on EC2 instance

### ISSUE THREAD

**Issue by Sarickshah** [pydata/pandas-gbq#95]
Is there any way to streaming insert from ec2? When I run as a cron job the streaming insert doesn't work but if I manually run it myself it does.... anyone have insight as to if this is impossible or can guide in any way?

**Comment by tswast** [comment]
How are you authenticating on your EC2 instance currently?

The easiest way to authenticate is with [Application Default Credentials](https://cloud.google.com/docs/authentication/getting-started).

1. Create a service account on GCP.
2. Download a JSON service account key.
3. Transfer that JSON key to your EC2 instances.
4. Set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable.
5. Run your script on your EC2 instance.

**Comment by tswast** [comment]
Hi @Sarickshah, I’m closing this issue since I haven’t heard back. For issues like this that aren’t bugs in the library, you may get a better response by asking a question on StackOverflow.
