### ISSUE TITLE
Do not manually loop over all rows when encoding a dataframe as JSON

### ISSUE THREAD

**Issue by tswast** [pydata/pandas-gbq#96]
See: https://github.com/pydata/pandas-gbq/pull/25#discussion_r155355165

Currently the code loops over each row to encode it as JSON. This could be sped up by calling `to_json()` on the whole dataframe instead.

**Comment by tswast** [comment]
Calling `to_json()` on the whole dataframe gives an actual JSON object, not newline-delimited JSON. This will become much easier if/when BigQuery supports a column-oriented data format such as Parquet.

**Comment by tswast** [comment]
Cool, thanks @maxim-lian

**Comment by tswast** [comment]
Ah, yeah CSV might be the way to go for now.

**Comment by maxim-lian** [comment]
CSV also smaller! And no nesting possible so no loss there

But if json is preferred, I think you can use `orient=records`

**Comment by tswast** [comment]
Looks like something like this should work to avoid having to write to a temporary file.

```python
def encode_chunk(df):
    """Return a file-like object of CSV-encoded rows.

    Args:
      df (pandas.DataFrame): A chunk of a dataframe to encode
    """
    csv_buffer = six.StringIO()
    df.to_csv(
        csv_buffer, index=False, header=False, encoding='utf-8',
        date_format='%Y-%m-%d %H:%M')

    # Convert to a BytesIO buffer so that unicode text is properly handled.
    # See: https://github.com/pydata/pandas-gbq/issues/106
    body = csv_buffer.getvalue()
    if isinstance(body, bytes):
        body = body.decode('utf-8')
    body = body.encode('utf-8')
    return six.BytesIO(body)
```

**Comment by tswast** [comment]
Closed by https://github.com/pydata/pandas-gbq/pull/117
